# Generated by Django 5.0.3 on 2024-04-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews_remove_movie_description_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Commenting Date')),
                ('comments', models.CharField(choices=[('P', 'Positive'), ('N', 'Neutral'), ('B', 'Negative')], default='P', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Movie', max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Adventure', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Movie', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2005),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie'),
        ),
    ]
